import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#a73a00',
        'secondary-fixed-dim': '#e9c400',
        'surface-container-low': '#f3f4f5',
        'primary-fixed': '#ffdbce',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#c8c6c5',
        'secondary-fixed': '#ffe170',
        'surface-container': '#edeeef',
        'secondary-container': '#fdd400',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#1c1b1b',
        'on-secondary-fixed': '#221b00',
        'tertiary-fixed': '#e5e2e1',
        'on-tertiary-fixed-variant': '#474746',
        'on-secondary-fixed-variant': '#544600',
        'outline': '#8f7065',
        'primary': '#a73a00',
        'secondary': '#705d00',
        'surface-container-high': '#e7e8e9',
        'error': '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'surface-bright': '#f8f9fa',
        'tertiary': '#5f5e5e',
        'tertiary-container': '#949292',
        'surface-dim': '#d9dadb',
        'on-secondary': '#ffffff',
        'on-primary-container': '#521800',
        'background': '#f8f9fa',
        'on-secondary-container': '#6f5c00',
        'surface-container-highest': '#e1e3e4',
        'inverse-surface': '#2e3132',
        'surface-variant': '#e1e3e4',
        'surface': '#f8f9fa',
        'error-container': '#ffdad6',
        'inverse-primary': '#ffb59a',
        'primary-fixed-dim': '#ffb59a',
        'outline-variant': '#e4beb1',
        'on-primary-fixed': '#370e00',
        'primary-container': '#ff5c00',
        'inverse-on-surface': '#f0f1f2',
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#802a00',
        'on-surface': '#191c1d',
        'on-tertiary-container': '#2c2b2b',
        'on-surface-variant': '#5b4137',
        'on-background': '#191c1d',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'stack-lg': '48px',
        'stack-md': '24px',
        'stack-sm': '12px',
        'section-gap': '64px',
        'margin-mobile': '16px',
        'container-max': '1280px',
        'stack-xs': '4px',
        'base': '8px',
        'gutter': '24px',
      },
      fontFamily: {
        'headline-lg-mobile': ['"Archivo Narrow"', 'sans-serif'],
        'display-hero-mobile': ['"Archivo Narrow"', 'sans-serif'],
        'headline-lg': ['"Archivo Narrow"', 'sans-serif'],
        'body-lg': ['"Be Vietnam Pro"', 'sans-serif'],
        'headline-md': ['"Archivo Narrow"', 'sans-serif'],
        'display-hero': ['"Archivo Narrow"', 'sans-serif'],
        'label-caps': ['"Be Vietnam Pro"', 'sans-serif'],
        'label-category': ['"Be Vietnam Pro"', 'sans-serif'],
        'body-md': ['"Be Vietnam Pro"', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '30px', fontWeight: '600' }],
        'display-hero-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-hero': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-category': ['14px', { lineHeight: '18px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
export default config
